### ISSUE TITLE
Getting rid of decoys

### ISSUE THREAD

**Issue by calkan** [coinami/coinami-pro#2]
We can get rid of decoys. It is costly to create and maintain them for each different read length anyway.

Instead:

i <- 0;
while i<NUMBER_OF_DECOYS do

  pick a random line in the BAM file; except the unmapped reds;
  apply the MD and CIGAR information on the read, and compare with the reported location in the reference
  if apply(read, MD, CIGAR) = reference[location] then
    i++;
  else
      BAM file is invalid;  do not sign
     break
  endif

 endwhile

 if i=NUMBER_OF_DECOYS then
  sign
 endif

**Comment by calkan** [comment]
this approach gets rid of decoys, making BAM verification and rejecting fabricated results faster.

**Comment by calkan** [comment]
here is an initial implementation of decoy-free validator:  https://github.com/calkan/checkbam

I'm not proud of the code, but it seems it works. I will test more. This can be merged with the demuxer as well. Another good idea to have it is implementing the BamHash method: http://bioinformatics.oxfordjournals.org/content/32/1/140.full

there is code for it, but it would be better if we can do the same calculations while demuxing. No need to traverse the same BAM file twice. The "checkbam" part can be initially run for fast rejection of forged BAMs, and the full demux/bamhash can be the final check.

**Comment by coinami** [comment]
I think we can close this issue.
